import { getModelName } from '../models';
import type { PipelineContext, SectionResult } from '../types';

/**
 * Step 5: Format output as Markdown
 * Includes links to source posts
 */
export function formatMarkdown(ctx: PipelineContext): PipelineContext {
  const data = ctx.translatedData || ctx.extractedData;

  if (!data) {
    throw new Error('No data available to format');
  }

  let markdown = '';

  ctx.sections.forEach((section) => {
    markdown += `## ${section.title}\n\n`;
    const sectionResult: SectionResult = data[section.id] || { items: [], sourcePosts: [] };
    const { items } = sectionResult;

    if (items.length === 0) {
      markdown += `*No significant findings.*\n\n`;
    } else {
      items.forEach((item) => {
        // Title with link if available
        if (item.sourceUrl) {
          markdown += `### [${item.title}](${item.sourceUrl})\n`;
        } else {
          markdown += `### ${item.title}\n`;
        }
        markdown += `${item.summary}\n\n`;
      });
    }
    
    markdown += '---\n\n';
  });

  // Add footer with metadata
  const modelName = getModelName(ctx.config);
  const footer = `> Generated by ${ctx.config.provider} (${modelName}) | ${ctx.config.reportLanguage || 'English'}`;

  return { ...ctx, markdown: markdown + footer };
}

/**
 * Generate report title
 */
export function generateReportTitle(): string {
  const now = new Date();
  const timeString = now.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  });
  return `Insight - ${now.toLocaleDateString()} (${timeString})`;
}
