import { getModelName } from '../models';
import type { PipelineContext, SectionResult, ReportSection } from '../types';

/**
 * Format items for OVERVIEW mode - analytical narrative
 */
function formatOverviewItems(items: SectionResult['items']): string {
  if (items.length === 0) {
    return `*No significant discussions found.*\n\n`;
  }

  let markdown = '';
  items.forEach((item) => {
    markdown += `**${item.title}**\n`;
    markdown += `${item.summary}`;
    if (item.sourceUrl) {
      markdown += ` [[source]](${item.sourceUrl})`;
    }
    markdown += `\n\n`;
  });
  return markdown;
}

/**
 * Format items for POSTS mode - list of curated posts
 */
function formatPostsItems(items: SectionResult['items']): string {
  if (items.length === 0) {
    return `*No relevant posts found.*\n\n`;
  }

  let markdown = '';
  items.forEach((item, index) => {
    const num = index + 1;
    if (item.sourceUrl) {
      markdown += `${num}. **[${item.title}](${item.sourceUrl})**\n`;
    } else {
      markdown += `${num}. **${item.title}**\n`;
    }
    markdown += `   ${item.summary}\n\n`;
  });
  return markdown;
}

/**
 * Step 5: Format output as Markdown
 * Uses different formatting based on section mode
 */
export function formatMarkdown(ctx: PipelineContext): PipelineContext {
  const data = ctx.translatedData || ctx.extractedData;

  if (!data) {
    throw new Error('No data available to format');
  }

  let markdown = '';

  ctx.sections.forEach((section: ReportSection) => {
    markdown += `## ${section.title}\n\n`;
    const sectionResult: SectionResult = data[section.id] || { items: [], sourcePosts: [] };
    const { items } = sectionResult;

    // Format based on section mode
    if (section.mode === 'posts') {
      markdown += formatPostsItems(items);
    } else {
      markdown += formatOverviewItems(items);
    }
    
    markdown += '---\n\n';
  });

  // Add footer with metadata
  const modelName = getModelName(ctx.config);
  const footer = `> Generated by ${ctx.config.provider} (${modelName}) | ${ctx.config.reportLanguage || 'English'}`;

  return { ...ctx, markdown: markdown + footer };
}

/**
 * Generate report title
 */
export function generateReportTitle(): string {
  const now = new Date();
  const timeString = now.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  });
  return `Insight - ${now.toLocaleDateString()} (${timeString})`;
}
